webtoon_board/toon/urls.py
from django.urls import path
from . import views

app_name = 'toon'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:toon_id>', views.toon_detail, name='detail'),
    #path('write', views.toon_create, name='create'),
    path('<int:comment_id>/edit', views.toon_edit, name='edit'),
    path('<int:comment_id>/delete', views.toon_delete, name='delete'),
]

webtoon_board/user/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('register', views.register, name='register'),
]

webtoon_board/webtoon_board/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("toon/", include('toon.urls')),
    path("user/", include('user.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    
] + static(settings.STATIC_URL, documnet_root=settings.STATIC_ROOT)

webtoon_board/toon/models.py
from django.db import models
from django.utils import timezone
from django.core import validators


class Author(models.Model):
    authorname = models.CharField(max_length=100)
    # authorid = models.AutoField(primary_key=True) 


class User(models.Model):
    # userid = models.AutoField(primary_key=True)
    username = models.CharField(max_length=50)
    
class Toon(models.Model):
    titleid = models.CharField(primary_key=True, max_length=50)
    titlename = models.CharField(max_length=50)
    starscore = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    startdate = models.DateTimeField(auto_now_add=True)
    genre = models.CharField(max_length=100, null=True)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    thumnail_URL = models.URLField()

    comment_user = models.ManyToManyField(User, through='Comment')


class Comment(models.Model):
    toon = models.ForeignKey(Toon, on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    comment = models.TextField(null=True)
    commentid = models.AutoField(primary_key=True)
    like = models.IntegerField(null=True)

webtoon_board/user/models.py
from django.db import models

# Create your models here.

webtoon_board/toon/forms.py
from django import forms
from .models import Comment, Toon

class ToonForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._widget_update()
    
    class Meta:
        model = Toon
        fields = ["titlename"]
        widgets = {
            'titlename': forms.TextInput(
                attrs={
                    'placeholder': "제목을 입력해주세요."
                }
            )
        }
    
    def _widget_update(self):
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._widget_update()
    
    class Meta:
        model = Comment
        fields = ["comment"]

    def _widget_update(self):
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

webtoon_board/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    username= forms.CharField(label="유저id", min_length=4, max_length=30,
                            widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="비밀번호",
                            widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="비밀번호 확인",
                            widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="이메일", required=False,
                            widget=forms.EmailInput(attrs={'class': 'form-control'}))


    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email')

webtoon_board/toon/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from .models import Toon, Comment, User
from .forms import CommentForm, ToonForm
from django.db.models import Prefetch
from django.urls import reverse

def index(request):
    toon_list = Toon.objects.all()
    return render(request, 'toon/index.html',
                    {"toon_list" : toon_list})

def toon_detail(request, toon_id):
    toon = Toon.objects.prefetch_related('author').get(titleid=toon_id)

    comment_set = toon.comment_set.prefetch_related('user').all()[:10]

    form = CommentForm()

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            comment = Comment(content = data['content'], toon=toon)
            comment.save()
        return redirect(reverse('toon:detail', kwargs={'toon_id':toon_id}))

    return render(request, 'toon/detail.html', 
    {'toon':toon, 'form':form, 'comment_set': comment_set})

def toon_edit(request, comment_id):
    comment = Comment.objects.get(commentid=comment_id)
    form = ToonForm(initial={
        'title':comment.commentid,
        'content':comment.comment,
    })
    if request.method == 'POST':
        form = ToonForm(request.POST)
        if form.is_valid():
            comment.comment = form.cleaned_data['comment']
            comment.save()
            return redirect(reverse('toon:detail', kwargs={'comment_id':comment_id}))
    return render(request, 'toon/edit.html', {'form':form})


from django.http import HttpRequest
def toon_delete(request:HttpRequest, comment_id):
    comment = get_object_or_404(Comment, commentid = comment_id)
    if request.method == 'POST':
        comment.delete()
    return redirect(request.headers['Referer'])

# from django.contrib.auth.decorators import login_required
# @login_required
# def comment_like(request, comment_id):
#     post = get_object_or_404(Post, id=comment_id)
#     user = request.user
#     comment = Comment.objects.get(user=user)

#     check_like_post = comment.like_posts.filter(id=comment_id)

#     comment.like_posts.add(post)
#     post.like_count += 1
#     post.save()

#     return redirect('toon:detail', comment_id)

webtoon_board/user/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.urls import reverse

from django.contrib.auth import authenticate, login, logout 
from django.utils import timezone

def index(request):
    # print(request.session)
    # for k, v in request.session.items():
    #     print(k, v)
    # request.session['visit_profile']= timezone.now().timestamp()
    resp =render (request, 'user/profile.html')
    resp.set_cookie('cookie_test', 'test_value')
    return resp

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect(reverse('user:index'))
    else:
        form = RegisterForm()
    return render(request, 'user/register.html', {'form':form})

webtoon_board/toon/templates/toon/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>naver webtoon review</title>
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}">
    {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous"> {% endcomment %}

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        main>.container {
            padding: 60px 15px 0;
        }
        
    </style>

</head>

<body class="d-flex flex-column h-100">
    {% include "toon/layouts/header.html" %}

    <!-- Begin page content -->
    <main class="flex-shrink-0">
        {% block main %}
        {% endblock %}
    </main>
    {% include "toon/layouts/footer.html" %}

    {% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script> {% endcomment %}
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
</body>

</html>

webtoon_board/toon/templates/toon/create.html
{% extends "./base.html" %}
{% block main %}
<div class="container">
    <div class="my-5">
        <div class="mb-5">
            <h3>글 쓰기</h3>
        </div>
        <div>
            <form action="{% url "toon:create" %}" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="fieldWrapper m-2">
                    {{ field.label_tag }} {{ field }}
                    </div>
                {% endfor %}
                <div class="mb-3 p-3">
                    <div style="float:right">
                        <button type="submit" class="btn btn-outline-success">Input</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

webtoon_board/toon/templates/toon/detail.html
{% extends "./base.html" %}
{% load static %}
{% block main %}
<div class="container">
    <div class="mt-5">
        <div>
            <p style="float:right">{{toon.genre}}</p>
            <a href = "https://comic.naver.com/webtoon/list?titleId={{toon.titleid}}">
                <h3>{{toon.titlename}} 보러가기</h3>
            </a>
        </div>
        <div>
            <img src="{% get_static_prefix %}bootstrap/image/Positive - {{ toon.titleid }}.png" alt="긍정" height = "400" width="600">
            <img src="{% get_static_prefix %}bootstrap/image/Negative - {{ toon.titleid }}.png" alt="부정" height = "400" width="600">
        </div>
        <div class="mt-5">
            <form action = "" method="POST" style="display:flex">
                {% csrf_token %}
                <div style="flex-grow:1;">
                    {{ form.content }}
                    <div id="content-help" class="form-text text-danger">
                        {{ form.content.errors }}
                    </div>
                    <input type="text" value="댓글을 입력해주세요" style="width:95%;">
                </div>
                <div>
                    <button type="submit" class="btn btn-outline-success">댓글작성</button>
                </div>
            </form>
        </div>
        {% comment %} {% for users in user %}
            {{user.username}}
        {% endfor %} {% endcomment %}
        
        {% for comment in comment_set %}
        <div class="mt-3" style="border:1px solid #e9e9e9">
            <div class="p-2">
                {{ comment.user.username }}
                <form href="/toon/{{ comment.commentid }}/delete"><button class="btn btn-danger" 
                    style="float:right; style=--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .5rem;">삭제</button></form>
                <form href="/toon/{{ toon.titleid }}/edit"><button class="btn btn-success" 
                    style="float:right; style=--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .5rem;">수정</button></form>
                <br>
                <br>
                {{comment.comment}} &nbsp;
                <p style="float:right"><button>추천하기</button>
                    &nbsp 추천수 : {{comment.like}}</p>
            </div>
        </div>
        {% endfor %}
        

    </div>
</div>
{% endblock %}

webtoon_board/toon/templates/toon/edit.html
{% extends "./base.html" %}
{% block main %}
<div class="container">
    <div class="my-5">
        <div class="mb-5">
            <h3>댓글 수정</h3>
        </div>
        <div>
            <form action="" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="fieldWrapper m-2">
                    {{ field.label_tag }} {{ field }}
                    </div>
                {% endfor %}
                <div class="mb-3 p-3">
                    <div style="float:right">
                        <button type="submit" class="btn btn-success">수정</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

webtoon_board/toon/templates/toon/index.html
{% extends "./base.html" %}
{% load static %}
{% block main %}

<div class="container">
    <div class="mt-5">
        <h2><b>네이버 웹툰</b></h2>
        <div class="list-group">
            <div class="row">
                {% for toon in toon_list %}
                <div class='col-4'>
                    <a href="/toon/{{toon.titleid}}" class="list-group-item list-group-item-action">
                        <div class="d-flex w-100 justify-content-between">
                            <img src= "{{toon.thumnail_URL}}" alt="웹툰사진" height = "200" width="280" style="display:block; margin:auto">
                        </div>
                        <h5 class="mb-1">{{toon.titlename}}</h5>
                        <h5 class="mb-1">
                                    {{toon.author.authorname}}
                                <small class="text-muted mb-1" style="float:right;">
                                    {{toon.startdate|date:"Y.m.d"}}
                                </small>
                            </h5>
                            <h5 class="mb-1">★ {{toon.starscore}}
                                <small class="text-muted mb-1" style="float:right;">
                                    {{toon.genre}}
                                </small>
                            </h5>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

webtoon_board/toon/templates/toon/layouts/footer.html
<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
        <span class="text-muted">출처 : 『https://comic.naver.com/index』</span>
    </div>
</footer>

webtoon_board/toon/templates/toon/layouts/header.html
{% load static %}
<header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-success fixed-top bg-success">
        <div class="container-fluid">
            <img src="{% static 'bootstrap/image/naverwebtoon.jpg' %}" alt="네이버웹툰사진" height = "50" width="50">
            &nbsp &nbsp &nbsp
            <a class="navbar-brand" href="#" style="color:white"><b>Naver Webtoon</b></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">

                    {% comment %}{% for cgr in category_list %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'cgr_prod' cgr.id %}">
                                {{cgr.title}}
                            </a>
                        </li>
                    {% endfor %} {% endcomment %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/toon" style="color:white"><b>액션</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/toon" style="color:white"><b>개그</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/toon" style="color:white"><b>일상</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/toon" style="color:white"><b>드라마</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/toon" style="color:white"><b>판타지</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/toon" style="color:white"><b>무협/사극</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/toon" style="color:white"><b>로맨스</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/toon" style="color:white"><b>감성</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/toon" style="color:white"><b>스포츠</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/toon" style="color:white"><b>스릴러</b></a>
                    </li>
                </ul>

                <div class='d-flex'>
                    {% if user.is_authenticated %}
                        <a class='btn btn-outline-dark' style='color:white;' href="{% url 'user:logout' %}">로그아웃</a>
                    {% else %}
                    <a class='btn btn-outline-dark' style='color:white;' href="{% url 'user:login' %}">로그인</a>
                    <a class='btn btn-warning' href="{% url 'user:register' %}">회원가입</a>
                    {% endif %}
                    <form class="d-flex">
                </form>
            </div>
        </div>
    </nav>
</header>

webtoon_board/user/templates/user/login.html
{% extends "toon/base.html" %}
{% block main %}
    <div class="container my-3">
        <form method="post" action="{% url 'user:login' %}">
            {% csrf_token %}
            <div class="fieldWrapper m-2">
                {{ form.username.label_tag }}
                <input type="text" class="form-control" name="{{ form.username.name }}" id="{{ form.username.name }}" value="{{ form.username.value|default_if_none:'' }}">
            </div>

            <div class="fieldWrapper m-2">
                {{ form.password.label_tag }}

                <input type="password" class="form-control" name="{{ form.password.name }}" id="{{ form.password.name }}" value="{{ form.password.value|default_if_none:'' }}">
            </div>

            <div class="mb-3 p-3">
                <div style="float:right">
                    <button type="submit" class="btn btn-primary">로그인</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

webtoon_board/user/templates/user/profile.html
{% extends "toon/base.html" %}
{% block main %}
    <div class="container">
        <div class="mt-5 contents-wrap">
            <h3 class="nav-loc">
                나의 정보
            </h3>

            <div class="container">
                {{ user }}
            </div>

        </div>
    </div>
{% endblock %}

webtoon_board/user/templates/user/register.html
{% extends "toon/base.html" %}
{% block main %}
<div class="container">
    <style>
        .nav-loc {
            color: #8b8b8b;
        }
    </style>
    <div class="mt-5 contents-wrap">
        <h3 class="nav-loc">
            회원가입
        </h3>

        <div class="container">
            <div class="contents">
                <form action="{% url "user:register" %}" method="POST">
                {% csrf_token %}

                {% for field in form %}
                <div class="fieldWrapper m-2 my-4">
                    {{ field.label_tag }} {{ field }}
                </div>
                {% endfor %}

                    <div class="mb-3 p-3">
                        <div style="float:right">
                            <button type="submit" class="btn btn-outline-success">회원가입</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}