mydjango_board/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:board_id>', views.board_detail, name='detail'),
    path('write', views.board_create, name='create'),
    path('<int:board_id>/edit', views.board_edit, name='edit'),
    path('<int:board_id>/delete', views.board_delete, name='delete'),
]

mydjango_board/mydjango_board/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("board/", include('board.urls')),
    path("user/", include('user.urls')),
] + static(settings.STATIC_URL, documnet_root=settings.STATIC_ROOT)

mydjango_board/board/models.py
from django.db import models
from django.utils import timezone
from django.core import validators

# Create your models here.


class Board(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255,
                            validators=[
                                validators.MinLengthValidator(3, "최소 3글자 이상은 입력해주셔야합니다.")
                            ])
    content = models.TextField("내용", validators=[
        validators.MinLengthValidator(10, "최소 10글자 이상은 입력해주셔야 합니다."),
    ])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    is_deleted = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.id} - {self.title}"
    
class Comment(models.Model):
    #id = models.AutoField(primary_key=True)
    content = models.CharField(max_length=255,
                                validators=[
                                    validators.MinLengthValidator(3, "최소 3글자 이상은 입력해주셔야합니다.")
                            ])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    board = models.ForeignKey(Board, on_delete=models.SET_NULL, null=True)

mydjango_board/board/forms.py
from django import forms
from .models import Board, Comment

class BoardForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._widget_update()
    
    class Meta:
        model = Board
        fields = ["title", "content"]
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'placeholder': "제목을 입력해주세요."
                }
            )
        }
    
    def _widget_update(self):
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._widget_update()
    
    class Meta:
        model = Comment
        fields = ["content"]

    def _widget_update(self):
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

mydjango_board/board/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Board, Comment
from .forms import BoardForm, CommentForm

from django.urls import reverse

def index(request):
    board_list = Board.objects.filter(is_deleted = 0).all()
    return render(request, 'board/index.html',
                    {"board_list" : board_list})

def board_detail(request, board_id):
    board = Board.objects.filter(is_deleted = 0).prefetch_related('comment_set').get(id=board_id)
    #comment_list = Comment.object.filter(board_id=board_id).all()
    
    form = CommentForm()

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            comment = Comment(content = data['content'], board=board)
            comment.save()
        return redirect(reverse('board:detail', kwargs={'board_id':board_id}))

    return render(request, 'board/detail.html', {'board':board, 'form':form})

def board_create(request):
    #print(dir(request))

    form = BoardForm()
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            # board = Board(
            #     title = data['title'],
            #     content = data['content']
            # )
            # board.save()
            form.save(commit=True)
            return redirect(reverse('board:index'))
            #return redirect('/board')

    return render(request, 'board/create.html', {'form':form})

def board_edit(request, board_id):
    board = Board.objects.filter(is_deleted = 0).get(id=board_id)
    form = BoardForm(initial={
        'title':board.title,
        'content':board.content
    })
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            board.title = form.cleaned_data['title']
            board.content = form.cleaned_data['content']
            board.save()
            return redirect(reverse('board:detail', kwargs={'board_id':board_id}))
    return render(request, 'board/edit.html', {'form':form})

def board_delete(request, board_id):
    board = Board.objects.get(id = board_id)
    board.is_deleted = True
    board.save()
    #board.delete()
    return redirect(reverse('board:index'))

mydjango_board/user/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.urls import reverse

from django.contrib.auth import authenticate, login, logout 
from django.utils import timezone

def index(request):
    # print(request.session)
    # for k, v in request.session.items():
    #     print(k, v)
    # request.session['visit_profile']= timezone.now().timestamp()
    resp =render (request, 'user/profile.html')
    resp.set_cookie('cookie_test', 'test_value')
    return resp

def register(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect(reverse('user:index'))
    return render(request, 'user/register.html', {'form':form})

# def user_profile(request):
#     return HttpResponse("""
#                         <h1>나의 프로필</h1>
#                         <ul>
#                             <li>이름 : 정훈</li>
#                             <li>별명 : JH</li>
#                         </ul>
#                         """)

mydjango_board/board/templates/board/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}">
    {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous"> {% endcomment %}

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        main>.container {
            padding: 60px 15px 0;
        }
    </style>

</head>

<body class="d-flex flex-column h-100">
    {% include "board/layouts/header.html" %}

    <!-- Begin page content -->
    <main class="flex-shrink-0">
        {% block main %}
        {% endblock %}
    </main>
    {% include "board/layouts/footer.html" %}

    {% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script> {% endcomment %}
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
</body>

</html>

mydjango_board/board/templates/board/create.html
{% extends "./base.html" %}
{% block main %}
<div class="container">
    <div class="my-5">
        <div class="mb-5">
            <h3>글 쓰기</h3>
        </div>
        <div>
            <form action="{% url "board:create" %}" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="fieldWrapper m-2">
                    {{ field.label_tag }} {{ field }}
                    {% for error in field.errors %}
                    <div id="content-help" class="form-text text-danger">{{ field.errors }}</div>
                    {% endfor %}
                    </div>
                {% endfor %}
                <div class="mb-3 p-3">
                    <div style="float:right">
                        <button type="submit" class="btn btn-outline-success">Input</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mydjango_board/board/templates/board/detail.html
{% extends "./base.html" %}
{% block main %}
<div class="container">
    <div class="mt-5">

        <h3>{{board.title}}</h3>

        <a href="/board/{{ board.id }}/edit"><button class="btn btn-success">수정</button></a>
        <a href="/board/{{ board.id }}/delete"><button class="btn btn-danger">삭제</button></a>

        <div class="mt-3" style="border:1px solid #e9e9e9">
            <div class="p-2">
                {{board.content}}
            </div>

        </div>
        <div class="mt-5">
            <form action = "" method="POST" style="display:flex">
                {% csrf_token %}
                <div style="flex-grow:1;">
                    {{ form.content }}
                    <div id="content-help" class="form-text text-danger">{{ form.content.errors }}</div>
                </div>
                <div>
                    <button type="submit" class="btn btn-outline-success">댓글작성</button>
                </div>
            </form>
        </div>

        <div class="my-5">
            {% for comment in board.comment_set.all %}
            {{comment.content}} &nbsp; <br>
            {% endfor %}
        </div>

    </div>
</div>
{% endblock %}

mydjango_board/board/templates/board/edit.html
{% extends "./base.html" %}
{% block main %}
<div class="container">
    <div class="my-5">
        <div class="mb-5">
            <h3>글 수정</h3>
        </div>
        <div>
            <form action="" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="fieldWrapper m-2">
                    {{ field.label_tag }} {{ field }}
                    {% for error in field.errors %}
                    <div id="content-help" class="form-text text-danger">{{ field.errors }}</div>
                    {% endfor %}
                    </div>
                {% endfor %}
                <div class="mb-3 p-3">
                    <div style="float:right">
                        <button type="submit" class="btn btn-success">수정</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mydjango_board/board/templates/board/index.html
{% extends "./base.html" %}
{% block main %}
<div class="container">
    <div class="mt-5">
        <h2>게시글 리스트</h2>
        <div class="list-group">
            {% for board in board_list %}
            <a href="/board/{{board.id}}" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{board.title}}</h5>
                    <small class="text-muted">
                        {{board.created_at|date:"Y.m.d"}}
                    </small>
                </div>
                <p class="mb-1">{{board.content|truncatechars:30}}</p>
            </a>

            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

mydjango_board/board/templates/board/layouts/footer.html
<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
        <span class="text-muted">Place sticky footer content here.</span>
    </div>
</footer>

mydjango_board/board/templates/board/layouts/header.html
<header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">MY BOARD</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/board">게시글</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/board/write">글쓰기</a>
                    </li>
                </ul>

                <div class='d-flex'>
                    {% if user.is_authenticated %}
                        <a class='btn btn-outline-dark' style='color:white;' href="{% url 'user:logout' %}">로그아웃</a>
                    {% else %}
                    <a class='btn btn-outline-dark' style='color:white;' href="{% url 'user:login' %}">로그인</a>
                    <a class='btn btn-warning' href="{% url 'user:register' %}">회원가입</a>
                    {% endif %}
                {% comment %} <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form> {% endcomment %}
            </div>
        </div>
    </nav>
</header>

mydjango_board/user/templates/user/login.html
{% extends "board/base.html" %}
{% block main %}
    <div class="container my-3">
        <form method="post" action="{% url 'user:login' %}">
            {% csrf_token %}
            <div class="fieldWrapper m-2">
                {{ form.username.label_tag }}
                <input type="text" class="form-control" name="{{ form.username.name }}" id="{{ form.username.name }}" value="{{ form.username.value|default_if_none:'' }}">
                {% for error in form.username.errors %}
                    <div id="content-help" class="form-text text-danger">{{ field.errors }}</div>
                {% endfor %}
            </div>

            <div class="fieldWrapper m-2">
                {{ form.password.label_tag }}

                <input type="password" class="form-control" name="{{ form.password.name }}" id="{{ form.password.name }}" value="{{ form.password.value|default_if_none:'' }}">
                {% for error in form.password.errors %}
                    <div id="content-help" class="form-text text-danger">{{ field.errors }}</div>
                {% endfor %}
            </div>

            <div class="mb-3 p-3">
                <div style="float:right">
                    <button type="submit" class="btn btn-primary">로그인</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

mydjango_board/user/templates/user/profile.html
{% extends "board/base.html" %}
{% block main %}
    <div class="container">
        <div class="mt-5 contents-wrap">
            <h3 class="nav-loc">
                나의 정보
            </h3>

            <div class="container">
                {{ user }}
            </div>

        </div>
    </div>
{% endblock %}

mydjango_board/user/templates/user/register.html
{% extends "board/base.html" %}
{% block main %}
<div class="container">
    <style>
        .nav-loc {
            color: #8b8b8b;
        }
    </style>
    <div class="mt-5 contents-wrap">
        <h3 class="nav-loc">
            회원가입
        </h3>

        <div class="container">
            <div class="contents">
                <form action="{% url "user:register" %}" method="POST">
                {% csrf_token %}

                {% for field in form %}
                    <div class="fieldWrapper m-2 my-4">
                    {{ field.label_tag }} {{ field }}
                    {% for error in field.errors %}
                        <div id="content-help" class="form-text text-danger">{{ error }}</div>
                        {% endfor %}
                        </div>
                    {% endfor %}

                    <div class="mb-3 p-3">
                        <div style="float:right">
                            <button type="submit" class="btn btn-outline-success">회원가입</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}